# Generated by Django 4.2.23 on 2025-11-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_fix_tenantuser_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bundle_id', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(choices=[('ios', 'iOS - Apple App Store'), ('android', 'Android - Google Play')], max_length=20)),
                ('developer_name', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('draft', 'Draft')], default='active', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField(default=0, help_text='Current store rating (0-5)')),
                ('reviews_count', models.IntegerField(default=0)),
                ('downloads_count', models.BigIntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aso_apps', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('tenant', 'bundle_id', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title for screenshot in specific locale', max_length=255)),
                ('image_url', models.URLField()),
                ('locale', models.CharField(blank=True, help_text='Locale for localized screenshots', max_length=20)),
                ('position', models.IntegerField(default=1, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='aso.app')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('helpful_count', models.IntegerField(default=0)),
                ('unhelpful_count', models.IntegerField(default=0)),
                ('response', models.TextField(blank=True, help_text='Developer response to review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='aso.app')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='open', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('estimated_impact', models.CharField(blank=True, help_text='e.g., +5% downloads', max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_tasks', to='aso.app')),
            ],
            options={
                'ordering': ['-priority', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('rating', 'Rating'), ('reviews', 'Review Count'), ('downloads', 'Downloads'), ('rank', 'Store Rank'), ('impressions', 'Impressions'), ('installs', 'Installs')], max_length=20)),
                ('value', models.FloatField()),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='aso.app')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('app', 'metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CompetitorApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_name', models.CharField(max_length=255)),
                ('competitor_bundle_id', models.CharField(max_length=255)),
                ('platform', models.CharField(choices=[('ios', 'iOS - Apple App Store'), ('android', 'Android - Google Play')], max_length=20)),
                ('rating', models.FloatField(default=0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('downloads_count', models.BigIntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='aso.app')),
            ],
            options={
                'ordering': ['-rating'],
                'unique_together': {('app', 'competitor_bundle_id')},
            },
        ),
        migrations.CreateModel(
            name='AppListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(choices=[('en_US', 'English (US)'), ('en_GB', 'English (UK)'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('ja', 'Japanese'), ('zh_CN', 'Chinese (Simplified)'), ('pt_BR', 'Portuguese (Brazil)')], default='en_US', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('keywords_string', models.CharField(help_text='Keywords for ASO (comma-separated)', max_length=500)),
                ('promotional_text', models.CharField(blank=True, max_length=170)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='aso.app')),
            ],
            options={
                'ordering': ['locale'],
                'unique_together': {('app', 'locale')},
            },
        ),
        migrations.CreateModel(
            name='AppKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0, help_text='Current ranking position in search results')),
                ('search_volume', models.IntegerField(default=0, help_text='Monthly search volume estimate')),
                ('difficulty', models.IntegerField(default=0, help_text='Competition difficulty 0-100')),
                ('tracking', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='aso.app')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('app', 'keyword')},
            },
        ),
    ]
