# Generated by Django 4.2.23 on 2025-11-07 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_content_items', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_faqs', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='keywordcluster',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_keyword_clusters', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='site',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_sites', to='tenants.tenant'),
        ),
    ]
