# Generated by Django 4.2.23 on 2025-11-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_contentitem_tenant_alter_faq_tenant_and_more'),
        ('seo', '0002_site_unique_domain_per_tenant'),
    ]

    operations = [
    ]
