# Generated by Django 4.2.23 on 2025-11-13 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_merge_20251107_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacklinkProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_backlinks', models.IntegerField(default=0)),
                ('unique_domains', models.IntegerField(default=0)),
                ('avg_domain_rating', models.FloatField(default=0)),
                ('dofollow_backlinks', models.IntegerField(default=0)),
                ('nofollow_backlinks', models.IntegerField(default=0)),
                ('toxic_backlinks_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backlink_profile', to='seo.site')),
            ],
        ),
        migrations.CreateModel(
            name='LinkOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_url', models.URLField()),
                ('prospect_domain', models.CharField(max_length=255)),
                ('anchor_text', models.CharField(max_length=255)),
                ('target_page', models.URLField()),
                ('domain_rating', models.IntegerField(default=0)),
                ('page_authority', models.IntegerField(default=0)),
                ('traffic_estimate', models.IntegerField(default=0)),
                ('relevance_score', models.IntegerField(default=0, help_text='0-100 score')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('failed', 'Failed'), ('secured', 'Secured')], default='open', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('outreach_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_opportunities', to='seo.site')),
            ],
            options={
                'ordering': ['-priority', '-relevance_score'],
                'indexes': [models.Index(fields=['site', 'status'], name='seo_linkopp_site_id_8d2352_idx'), models.Index(fields=['site', 'priority'], name='seo_linkopp_site_id_cb76c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetitorBacklink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_domain', models.URLField()),
                ('source_url', models.URLField()),
                ('target_url', models.URLField()),
                ('anchor_text', models.CharField(blank=True, max_length=255)),
                ('domain_rating', models.IntegerField(default=0)),
                ('page_authority', models.IntegerField(default=0)),
                ('is_dofollow', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitor_backlinks', to='seo.site')),
            ],
            options={
                'ordering': ['-domain_rating'],
                'unique_together': {('site', 'source_url', 'target_url')},
            },
        ),
        migrations.CreateModel(
            name='Backlink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField()),
                ('target_url', models.URLField()),
                ('anchor_text', models.CharField(blank=True, max_length=255)),
                ('domain_rating', models.IntegerField(default=0, help_text='0-100 scale')),
                ('page_authority', models.IntegerField(default=0, help_text='0-100 scale')),
                ('status', models.CharField(choices=[('active', 'Active'), ('lost', 'Lost'), ('broken', 'Broken'), ('spam', 'Spam')], default='active', max_length=20)),
                ('is_dofollow', models.BooleanField(default=True)),
                ('is_external', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlinks', to='seo.site')),
            ],
            options={
                'ordering': ['-domain_rating', '-last_checked'],
                'indexes': [models.Index(fields=['site', 'status'], name='seo_backlin_site_id_3b16c7_idx'), models.Index(fields=['site', 'domain_rating'], name='seo_backlin_site_id_2ed988_idx')],
                'unique_together': {('site', 'source_url', 'target_url')},
            },
        ),
    ]
