# Generated by Django 4.2.23 on 2025-11-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('marketing', 'Marketing'), ('business', 'Business'), ('tutorial', 'Tutorials'), ('announcement', 'Announcements')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, help_text="URL for the post's featured image"),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short summary for previews and social sharing'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('post', 'Social Post'), ('article', 'Blog Article'), ('news', 'News Update'), ('tutorial', 'Tutorial'), ('ad', 'Advertisement')], default='post', max_length=20),
        ),
    ]
